package com.john.history.history.database;

import android.arch.persistence.room.Entity;
import android.arch.persistence.room.Ignore;
import android.arch.persistence.room.Index;
import android.arch.persistence.room.PrimaryKey;
import android.arch.persistence.room.Room;

import java.util.Date;

/**
 * Created by Administrator on 2018/1/28.
 */

@Entity(tableName = "history", indices = {@Index(value = {"date"}, unique = true)})
public class EventEntry {

    /**
     * Makes sure the id is the primary key (ensures uniqueness), is auto generated by {@link Room}.
     */
    @PrimaryKey(autoGenerate = true)
    private int id;
    private String date;
    private String event;


    @Ignore
    public EventEntry(String date, String event) {
        this.event = event;
        this.date = date;

    }

    // Constructor used by Room to create WeatherEntries
    public EventEntry(int id, String date, String event) {
        this.id = id;
        this.event = event;
        this.date = date;

    }

    public int getId() {
        return id;
    }

    public String getDate() {
        return date;
    }

    public String getEvent() {
        return event;
    }


}

